### ISSUE TITLE
[intersection-observer] `createVisibilityObserver` does not work with `display: contents`

### ISSUE THREAD

**Issue by Enteleform** [solidjs-community/solid-primitives#116]
# Expected

Elements with `display: contents` will trigger the visibility observer and render in their usual manner.

# Actual

Elements with `display: contents` do not trigger the visibility observer and they are not rendered at all.

https://user-images.githubusercontent.com/10906415/166436977-aa9e9fc9-e56a-4ccc-adef-6e601a16dfa1.mp4

# Reproduction
https://codesandbox.io/s/solid-primitives-intersection-observer-forked-7cc2vz?file=/src/index.tsx

**Comment by davedbase** [comment]
Hmmm interesting. I too was a bit unaware of display: contents. I've never had a use case for that. I did a bit of research and other React based primitives have stumbled on the same issue: https://github.com/thebuilder/react-intersection-observer/issues/421

I'm not sure if there's a viable alternative to this issue. According to the definition contents: `Makes the container disappear, making the child elements children of the element the next level up in the DOM`. So the issue is likely that the container isn't in viewport at all and it's skipping to the next element and hence never displaying at all.

I kind of agree with the react hooks author that this is quite the edge case, but if there's an easy solution that doesn't include hammering the primitive with more LoCs, I'd certainly entertain it.

Ideas anyone?

**Comment by Enteleform** [comment]
@thetarnav

Hey, haven't figured out a workaround. I encountered the issue while working on [astro-portal](https://github.com/Enteleform/lazy-portal/tree/main/packages/astro-portal), and I ended up just setting the portal's width & height to 100% to offload the sizing responsibility to the container where the portal is placed.

Dunno what the best way to approach this would be, I've encountered `display: contents` issues in several contexts (*portals, table components, drag-&-drop libraries*) and haven't seen any of them resolved. Is it that the DOM API doesn't have adequate means of interacting with elements with that property?

**Comment by thetarnav** [comment]
> Is it that the DOM API doesn't have adequate means of interacting with elements with that property?

Yeah, the IO is just ignoring elements with that style. Similarly, you cannot put any CSS transform on that element successfully.
I also had some issues with astro islands with it. This is what I had to do:
```ts
const resolved = children(() => props.children)

onMount(() => {
	let _ref = resolved()
	let ref!: HTMLElement

	while (_ref instanceof HTMLElement && !ref) {
		if (getComputedStyle(_ref).display === "contents") _ref = _ref.firstChild
		else ref = _ref
	}
	if (!ref) {
		warn("Parallax children must be a single element")
		return
	}
	// do sth with ref
}
```
So I don't know if there is anything we could do in the primitive implementation to make this easier. Each usecase will require a different workaround.

**Comment by Enteleform** [comment]
Gotcha. Ok if you want to close the issue that's fine, would have closed it myself but you mentioned that you might add a warning so figured I'd leave the closing to you in case you want to use this as a reference for that. I appreciate that you guys looked into it!
