### ISSUE TITLE
createDragAndDrop (Display & Media) vs createDropzone (Browser APIs)

### ISSUE THREAD

**Issue by frixaco** [solidjs-community/solid-primitives#126]
There's an `createDropzone` primitive in Browser APIs section ([upload](https://github.com/solidjs-community/solid-primitives/tree/main/packages/upload#readme)). Currently, `createDropzone` provides running user callbacks during each drag event (async/sync) (dragstart, dragover, ...., drag, drop), returns a `ref` to add drag'n'drop **files** functionality for to an element and a couple of helpers to remove selected files.

And there's a planned primitive called `createDragAndDrop` that I just noticed. A few questions:
1. Can `createDropzone` be renamed to `createDragAndDrop` and exist as a separate primitive (maybe with some additional features)?
2. If no, how should `createDragAndDrop` look like?

**Comment by thetarnav** [comment]
I haven't put it there, but I'm assuming that the `createDragAndDrop` primitive would be providing an interface for dragging html elements around/between containers. Similar to [solid-dnd](https://github.com/thisbeyond/solid-dnd) but lower-level if that makes sense. It's just a guess though, @davedbase should have a better idea.

**Comment by davedbase** [comment]
Yeah I think we want to port over solid-dnd's primitives because IMO they are well designed. @frixaco did you want to take a look at that effort and compare/contrast your approach? We'd be very happy to have someone take this on as long as we can all agree on the design and maintenance plan for them.

Ps. I personally had a lot of success with the solid-dnd pattern. The way it has useDragDropContext, createDraggable and createDroppable is pretty powerful ad elegant.

**Comment by frixaco** [comment]
@davedbase Yeah, I saw it too but didn't really look at the source code, since I just started learning Solid:)
I'll look at it then and see how can I improve my approach with `createDropzone` and get started with `createDragAndDrop` next. Feel free to leave any ideas, suggestions!
