### ISSUE TITLE
`createScrollObserver` should return a signal of `[number, number]`

### ISSUE THREAD

**Issue by nonphoto** [solidjs-community/solid-primitives#130]
It's useful to get the x position as well as y in some cases. Returning a tuple makes it easy to destructure.

**Comment by thetarnav** [comment]
Would returning a store-like object be helpful here? This way you would be able to listen to just the axis you need.
```ts
const scrollPos = createScrollPosition(window)
scrollPos.x // T: number
scrollPos.y // T: number

let ref: HTMLElement | undefined
const scrollPos = createScrollPosition(() => ref)
scrollPos.x // T: number | null
scrollPos.y // T: number | null
```
Or an object of accessors.
```ts
const { x, y } = createScrollPosition(window)
x() // T: number
y() // T: number

let ref: HTMLElement | undefined
const { x, y } = createScrollPosition(() => ref)
x() // T: number | null
y() // T: number | null
```

I'm more inclined to separating signals — rather than having one return `[x: number, y: number]` — because it's more convenient for people that only want to listen to `y` or `x`, which seems like a common usecase — the primitive is only providing `y` right now as it's what people mostly use.

**Comment by nonphoto** [comment]
I think returning a store seems like a good option. I'm coming from @use-gesture here which uses xy tuples, so I'm used to using `position[0]` or `position[1]` to get individual values or just destructuring. Whichever is more idiomatic for solid is fine though. Just keep in mind that I'm often using this in performance critical settings so I would prefer whichever option has less overhead. Stores might have better memory usage though as they wouldn't create a new array on each update.
