### ISSUE TITLE
createStorageSignal is null even with a initial value

### ISSUE THREAD

**Issue by TiagoCavalcante** [solidjs-community/solid-primitives#138]
```ts
// The type of value1 is boolean | null but it should be boolean
const [value1] = createStorageSignal("foo_bar", false);
// The type of value2 is correct, here a null is possible
const [value2] = createStorageSignal("foo_bar);
```

If you agree that the current behavior is wrong I can make a PR.

**Comment by atk** [comment]
Unfortunately, you never know if an external process overwrites the value in the storage; if that happens and the events are active, you will still receive a null value, so as a precaution, we left the types this way. If you're 100% sure, you can `!` the storage item you read instead of securing yourself against null.

**Comment by vanillacode314** [comment]
How about taking a factory function that returns a fallback value for cases when storage returns null?
