### ISSUE TITLE
[bug]: `combineProps` not merge refs as expected

### ISSUE THREAD

**Issue by fabien-ml** [solidjs-community/solid-primitives#262]
When using `combineProps` to merge refs the internal ref is `undefined`.

[codesandbox link](https://codesandbox.io/s/solid-hope-ui-forked-3lvvgd?file=/src/App.tsx)

```tsx
import { createEffect } from "solid-js";
import { combineProps } from "@solid-primitives/props";

function Button(props: any) {
  let ref: any;

  createEffect(() => {
    console.log(`inner: ${ref}`); // print "undefined"
  });

  return <button {...combineProps({ ref }, props)} />;
}

export default function App() {
  let ref: any;

  createEffect(() => {
    console.log(`outer: ${ref}`); // print "[object HTMLButtonElement]"
  });

  return <Button ref={ref}>Button</Button>;
}
```

**Comment by thetarnav** [comment]
Actually, it already works lol
You have to pass the `ref` prop as a function to `combineProps`, not the current value of your local variable.
Dong `<div ref={ref} />` compiles it to a function as well.
https://codesandbox.io/s/solid-hope-ui-forked-pubkfm?file=/src/App.tsx

Also, inlining spreads (`<div {...my_expression()} />`) should be avoided now as far as I know. Because the expression might get evaluated multiple times.

**Comment by fabien-ml** [comment]
> Also, inlining spreads (`<div {...my_expression()} />`) should be avoided now as far as I know. Because the expression might get evaluated multiple times.

I'm not sure to understand, how this can be done correctly ?

```tsx
<button {...combineProps()} />
```
