### ISSUE TITLE
Hydration issue

### ISSUE THREAD

**Issue by TomPichaud** [solidjs-community/solid-primitives#310]
Following https://github.com/withastro/astro/issues/6140

Hello,

I have a simple Solid component with a `usePrefersDark`. I expect the component to render with the default value and then hydrate with the correct value. It's only working properly with the `client:only` Astro property.

**Bug**: inlined value not updated on hydration

If I create my own signal and event listener it's working properly.

I'm willing to help to fix it but I would require some guidance. Thank you for your help.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tzjxcu?file=src/pages/index.astro

**Comment by thetarnav** [comment]
Hey, thanks for the issue.
I've heard that the media package is having some issues with hydration so I'm not supprised.
It has to be related to how `createMediaQuery` is implemented: https://github.com/solidjs-community/solid-primitives/blob/main/packages/media/src/index.ts#L47
I don't have much experience with hydration in solid so I might miss some issues there.
My guess is that the initial value of the signal gets ignored during hydration and effects will only take it's value on subsequent updates - but since the media query doesn't change - it is out of sync.
So the fix might be as simple as adding `createEffect` that will re-set the value of the signal. But if you set the signal to the value it had before - effects won't retrigger... So maybe you'd need to play with the `equals` option of signals to force update when the effect runs but only update if the signal is different afterwards...
This is interesting. wonder if there is a way to run some logic only during hydration, but keep it simple during normal CSR. Becasue there is no point in re-setting the signal value on CSR...

So that's about fixing it. But then testing. In out repo we have /dev directory with a simple vite project so it won't help much for hydration. The unit tests are either in SSR or CSR.
Maybe we need to figure out a way to better test hydration.

So probably the best way to test it would be to pnpm link the package and run it the the example astro project you've prepared.

So yeah, if you are down to help I would appreciate it :)
and ask away if you have any questions

**Comment by TomPichaud** [comment]
I feel like the issue runs deeper into solid. Take the following code:

```jsx
const prefersDark= usePrefersDark()
createEffect(() => {
	console.log(prefersDark())
})
return (
	<>
		<pre>prefersDark : {prefersDark() ? 'true' : 'false'}</pre>
		<pre textContent={`should be: ${prefersDark().toString()}`} />
	</>
)
```

The first one is bugged and showing the pre-render value until a new change is triggered; but the second one is synced correctly. How can you explain it ? _The log is also correct._

**Comment by thetarnav** [comment]
I think it is because of how hydration works. `textContent` attr is not being hydrated - the value is being reapplied on the client regardless of whether it was SSRd or not. For the actual text nodes - solid doesn't render them to the dom on the client if SSRd - but it runs the effects one time to subscribe to signals anyway.
You can imagine it as this:
```ts
let init = true
createRenderEffect(prev => {
  // track
  const v = signal()
  // quick return during hydration
  if (hydrating && init) {
    init = false
    return // I don't think the signal value is being returned here
  }
  // compare with prev value before updating dom
  if (prev !== v) el.innerHtml = v
  return v
})
```
So this produces a couple of problems for us:
1. the initial value of signals is ignored - I guess it is assumed to be the same on the server and client, otherwise updated after hydration (you don't want mismatches between server version and client, because it can break the hydration)
2. even if we update the value afterward the change might be stopped by the signal equality check, as you assigning the same value to a signal won't cause downstream updates
3. if we avoid it with `equals: false`, the same story will happen if we were to wrap the value with a memo, because if would have it's own equals check
    ```ts
    const memo = createMemo(() => signal())
    ```

I wonder whats the proper way to solve it.
Becasue I guess that if the initial value were `undefined` then we could easily set it to `false` or `true` and cause an update. Setting it to `false` or `true` on the server is lying in a sense - if you hydrate with different value then you are risking hydration errors. But haing it as `undefined` is a bit unhelpful.
Maybe we should remove the server fallback, and then youd have to decide how you want to handle `undefined` yourself?
```ts
<div
  style={{
    background: prefersDark() === undefined || prefersDark() === true ? "black" : "white"
  }}
/>
```

**Comment by TomPichaud** [comment]
I've tried with `undefined` and it doesn't seem to work either. It seems very complex.

The only working way is the following:

```jsx
const [prefersDark, setPrefersDark] = createSignal(
	isServer ? false : window.matchMedia('(prefers-color-scheme: dark)').matches,
	{equals: false}
)

createEffect(() => {
	const mql = window.matchMedia('(prefers-color-scheme: dark)')
	// Resetting the value
	setPrefersDark(window.matchMedia('(prefers-color-scheme: dark)').matches)
	mql.onchange = (e) => {
		if (e.matches) {
			setPrefersDark(true)
		} else {
			setPrefersDark(false)
		}
	}
})
return (
	<>
		<pre>prefersDark : {prefersDark() ? 'true' : 'false'}</pre>
		<pre textContent={`should be: ${prefersDark().toString()}`} />
	</>
)
```

**Comment by thetarnav** [comment]
For me it's one of these
```ts
export const createMediaQuery2 = (
  query: string,
  fallbackState: boolean = false,
  watchChange = true
): Accessor<boolean> => {
  if (process.env.SSR) {
    return () => fallbackState;
  }
  const mql = window.matchMedia(query);
  if (!watchChange) return () => mql.matches;
  let init = true;
  const [state, setState] = createSignal(mql.matches, {
    equals(a, b) {
      if (init) return (init = false);
      return a === b;
    }
  });
  createEffect(() => setState(mql.matches));
  makeEventListener(mql, "change", () => setState(mql.matches));
  return state;
};

export const createMediaQuery3 = (
  query: string,
  watchChange = true
): Accessor<boolean | undefined> => {
  if (process.env.SSR) {
    return () => undefined;
  }
  const mql = window.matchMedia(query);
  if (!watchChange) return () => mql.matches;
  const [state, setState] = createSignal<boolean | undefined>(undefined);
  createEffect(() => setState(mql.matches));
  makeEventListener(mql, "change", () => setState(mql.matches));
  return state;
};
```

**Comment by TomPichaud** [comment]
I've tested both ways and weirdly enough it's working on the following Astro properties `client:load` & `client:only` but still not working on `client:visible` & `client:idle`. The night is dark and full of terrors...

**Comment by TomPichaud** [comment]
I've tested both ways and weirdly enough it's now working on the following Astro properties:
- `client:only` as expected
- `client:load` fixed by your ways

But still not working on`client:visible` nor `client:idle`

_The night is dark and full of terrors..._

**Comment by thetarnav** [comment]
`client:load` got fixed becasue it runs first.
`createSharedRoot` works in a way that every time it's called it's returning the same signal - `createMediaQuery` runs only once. So the trick with resetting the signal value with createEffect will only work for instances that are loaded at this time - all the 
other that hydrate lated won't get re-triggered.
This makes `createSharedRoot` conceptually not suitable for island frameworks where the hydration can happen at different times. But it's not a problem specific to the shared root pattern. It'll be the same for any shared state between islands via signals.
So youd think that sharing a single signals between multiple islands would be a good pattern, but it turns out it is bad for the hydration? this is interesting.
I think the best way to solve this would be to not use the shared root during hydration.
https://stackblitz.com/edit/github-tzjxcu-xofarw?file=src/components/Test.tsx

**Comment by lxsmnsyc** [comment]
@TomPichaud This line

```js
isServer ? false : window.matchMedia('(prefers-color-scheme: dark)').matches,
```

will cause hydration issues because the initial state isn't consistent with the server. The initial state must be always `false`.

**Comment by TomPichaud** [comment]
I understand now, it all make sense. Thank you for taking the time to explain everything along the way, the experience is really nice!

**Comment by thetarnav** [comment]
> If `createSharedRoot` is being used somewhere else maybe it should also be addressed ?

yeah most likely

Maybe this should be a consideration of `createSharedRoot` itself because it's this kind of cases where the shared root is most useful, but deopting on hydration by default feels like breaking the contract - you cannot bet on there being only one instance as a time. So toggling this with an option would probably be the best.

**Comment by TomPichaud** [comment]
Having the same issue with `createStorageSignal` and others : still showing initial value in the DOM after hydration

Should we think of a wider solution for Solid Primitives to handle hydration ?

**Comment by thetarnav** [comment]
`createStorageSignal` is quite complicated I believe. cc @atk 
A wider solution would probably come after implementing that for a couple of primitives, but I'm interested in seeing some universal solutions.

**Comment by TomPichaud** [comment]
What do you think of using `createResource` with the following options:

```
{
   initialValue: true,
   ssrLoadFrom: 'initial',
   onHydrated: () => refetch()
}
```

**Comment by lxsmnsyc** [comment]
@TomPichaud I think I would just recommend using `createSignal` with `false` as an initialValue. `createResource` has many underlying features that will likely affect your application.

**Comment by thetarnav** [comment]
yeah I saw that idea on one of discord threads. But I don't think I would use `createResource` just to achieve that. It it made to handle promises, interact with suspense and who knows what else.
But I like the idea of abstracting this pattern into a reusable primitive:
```ts
import {
  createSignal,
  onMount,
  sharedConfig,
  Signal,
  SignalOptions,
} from "solid-js";

function createHydratedSignal<T>(
  serverValue: T,
  update: () => T,
  options: SignalOptions<T>
): Signal<T> {
  let init = !!sharedConfig.context;
  const [state, setState] = createSignal(init ? serverValue : update(), {
    ...options,
    equals(a, b) {
      if (init) return (init = false);
      return options.equals ? options.equals(a, b) : a === b;
    },
  });
  init && onMount(() => setState(() => update()));
  return [state, setState];
}
```

**Comment by TomPichaud** [comment]
Works like a charm!

**Comment by thetarnav** [comment]
It would be great to apply this pattern in different places of the library that might need it.
I don't know exactly what those places are, but it should be fairly easy to spot them. Pretty much every signal that has a potential of having a different initial value on the server and client. Hopefully not too many :)
I think the `createHydrateSignal` primitive should be added to `utils` for now, as it's more useful internally then when developing an app where you already know the env you're targeting.
For contributing you can start by forking the repository and creating a new branch for your changes. [The contributing guide](https://github.com/solidjs-community/solid-primitives/blob/main/CONTRIBUTING.md#tooling) should tell you about setting up the repo locally.
If you're not sure about something you can create a draft pull request with in-progress changes.
Looking at previous PRs to see what they have done and how they went is useful too.
