### ISSUE TITLE
createThrottle does not call on the leading edge

### ISSUE THREAD

**Issue by hangtwenty** [solidjs-community/solid-primitives#64]
Thanks for your awesome repository! 

I'm a little confused by `createThrottle`, as I expect a throttled function to fire immediately when it's the first invocation (in the throttle interval). [Here's a little example of what I mean](http://demo.nimius.net/debounce_throttle/).

Current behavior from `createThrottle`: the throttled function waits the full delay even if it's the first invocation. I would expect debounce to behave that way, but not throttle. 

To reproduce: use the CodeSandbox in the [`createThrottle` README](https://github.com/davedbase/solid-primitives/tree/main/packages/throttle).

<details><summary>Caveat: I figure it's "by design," but in that case I think the docs should be updated to clarify the behavior.</summary>

I'm aware sometimes people use the word "throttle" more generally; and/or, sometimes there's a flag like `{leading: true}` that enables/disables the leading-edge invocation. ([An example of that can be seen in lodash](https://github.com/lodash/lodash/blob/master/throttle.js#L35). Optionally, see also [p-debounce's `{before: true}` option](https://github.com/sindresorhus/p-debounce#before))

But I think in the general usage, "throttle" is contrasted against "debounce" — some references: [1](https://css-tricks.com/debouncing-throttling-explained-examples/), [2](https://css-tricks.com/the-difference-between-throttling-and-debouncing/), [3](https://stackoverflow.com/a/52192108/884640), [4](https://stackoverflow.com/a/62017005/884640), [5](https://dev.to/rxjs/debounce-vs-throttle-vs-audit-vs-sample-difference-you-should-know-1f21), [6](https://towardsdev.com/debouncing-and-throttling-in-javascript-8862efe2b563)  

So if `createThrottle` is _not_ going to call on the leading edge by default, perhaps to keep backwards-compatibility, I think the README/demo could be updated to emphasize the behavior.

</details>

**Comment by thetarnav** [comment]
Thank you for pointing out the issue and a bunch of resources to go though :)
I think that the current implementation is like this by design, but you're right that this should be represented in the readme/demo clearly.
Generally both our debounce & throttle are as simple as possible, but it is a good idea to add different/more configurable implementations as separate functions, e.g. `createLeadingThrottle`

**Comment by davedbase** [comment]
I'm in total agreement. This was certainly by design and should be clarified. Ideally I'd prefer have options in the primitive to specify leading however from researching the first implementation we couldn't get both perf and flexibility in the original. So having a separate primitive is likely the safest to maintain size, performance and flexibility. Really looking for a "clever" design here but I'm not sure it's totally possible. Suggestions are more than welcomed!

**Comment by hangtwenty** [comment]
Different functions makes sense to me too. (By the way, with the links I mentioned, I wasn't suggesting it should have a similar interface to them, rather just wanted to give context and maybe inspiration for option/function names.)
