### ISSUE TITLE
`makePersisted` removes initial field in store if stored data doesn't have that field before

### ISSUE THREAD

**Issue by Legend-Master** [solidjs-community/solid-primitives#643]
### Describe the bug

When using `makePersisted` to store settings, if I want to add in new settings in the future, initial settings get overridden

See the reproduction link, load in and click `Save Settings` and uncomment `// somethingElse: '123', // Uncomment this after save` in `index.tsx`, the page will still be showing

```
darkMode: false
fontSize: 16
```

Would expect it to be

```
darkMode: false
fontSize: 16
somethingElse: 123
```

### Minimal Reproduction Link

https://stackblitz.com/edit/github-xcjwur?file=src%2Findex.tsx,package.json,index.html

> ```ts
> const [settings, setSettings] = makePersisted(
>   createStore({
>     darkMode: false,
>     fontSize: 16,
>     // somethingElse: '123', // Uncomment this after save
>   })
> );
> ```

**Comment by atk** [comment]
Initial data is considered default data, to be overwritten by persisted data. If you delete a property that is merely in the defaults, you would expect it to remain deleted, right?

I am convinced that this is exactly how makePersisted is supposed to behave; otherwise it would be impossible to delete data that comes from the defaults. If you actually wanted that behavior, you probably want to use `mergeProps(defaults, settings)` instead of setting them as the defaults in your store.

**Comment by Legend-Master** [comment]
I am using something like this right now, just want to know if it's desired behavior or a bug, I think I understand the idea now, `makePersisted` simply replaces the data inside the store and only fallbacks to default data if no data stored

```ts
const defaultSettings = { darkMode: true }
const [setting, setSetting] = makePersisted(createStore(defaultSettings))
for (const [key, value] of Object.entries(defaultSettings)) {
	if (setting[key] === undefined) {
		setSetting(key, value)
	}
}
```

> otherwise it would be impossible to delete data that comes from the defaults.

Just being curios, is there any use cases where deleting a key from the default data is desired?

**Comment by atk** [comment]
This would needlessly persist the default settings that are already hard coded in your app, but if that's what you want, so be it.

> Just being curios, is there any use cases where deleting a key from the default data is desired?

We don't only persist settings. Imagine you persist the data of a form in sessionStorage using the FormData API together with the entries() method. The checkboxes are defined as `name=value` only if they are checked, otherwise they are removed from the data. Now imagine one checkbox is enabled by default. You would either have to change how to save the form data instead of simply using FormData or add a workaround.

The intentioned way to ensure that there are fallbacks is to define the fallbacks in code, not in the defaults. The defaults are solely there for the case there is nothing persisted in storage.
