### ISSUE TITLE
useKeyDownList holds character in list after release

### ISSUE THREAD

**Issue by onx2** [solidjs-community/solid-primitives#665]
### Describe the bug

I'm in firefox, I press shift + cmd + `<almost any character key>`, and it leaves the character key in the list.

In this image, between `[ "SHIFT", "META", "E" ]` and `[ "META", "E" ]` I released the `E` key.
<img width="294" alt="image" src="https://github.com/user-attachments/assets/f71fb5f6-d0f5-4089-8f1c-38b945cd44e3">

I noticed this happens with a few different character keys. When I click into the terminal, it console logs the empty array though so I think it might be related to built in functions associated with certain keys?

### Minimal Reproduction Link

https://stackblitz.com/edit/github-gqd2qu

**Comment by onx2** [comment]
To reproduce an issue when trying to bind to these keys and do something:

```tsx
  const keys = useKeyDownList();

  createEffect(() => {
    if (
      keys().includes("SHIFT") &&
      keys().includes("META") &&
      keys().includes("M")
    ) {
      console.log("SHIFT + META + M is pressed");
    }
  });
```

Pressing SHIFT META and M, then pressing SHIFT META will trigger the console log.

**Comment by onx2** [comment]
🤔 I wonder if we just cleared the array on blur of document if that would fix it?

**Comment by onx2** [comment]
This seems to be specifically an issue with `Meta` with `Alt`. There must be some default behavior in Mac or Firefox that is breaking things. FWIW this bug is also affecting `createShortcut`.

**Comment by maciek50322** [comment]
I think it has to do with system shortcuts, that very often use `Meta` key and I don't think you can override them in js... I'm on windows and when I do `SHIFT` + `META` + `M` it never logs, because it's shortcut to "Restore minimized windows on the desktop" and it definitely has higher priority over what happens inside browser. But for me it never adds `M` at the end, I think just system takes control, so there's no leftovers of the `M` to trigger only when  `SHIFT` + `META` are pressed. I guess on Mac it might work differently and the system doesn't take control immediately, so `keydown` is registered, but then `keyup` does not. Also I'm just guessing I don't have a Mac to test it.

**Comment by maciek50322** [comment]
Also there's already on blur that clears all the keys, but again different systems might have different blurs.

**Comment by onx2** [comment]
> I think it has to do with system shortcuts, that very often use `Meta` key and I don't think you can override them in js... 

Yeah that seems to be the case.  I wonder if there is a workaround for `createShortcut` though since it has an intended behavior after specific `keydown` events. What if we cleared the keydown list once the shortcut has been met? I think this could work but would maybe require an update to `useKeyDownList` to return `reset`.


This syntax is pretty common from what I've seen in solidjs, WDYT?
```tsx
const [keys, {reset}] useKeyDownList();
```

**Comment by maciek50322** [comment]
> What if we cleared the keydown list once the shortcut has been met? I think this could work but would maybe require an update to useKeyDownList to return reset.
>
>This syntax is pretty common from what I've seen in solidjs, WDYT?
> 
> ```tsx
> const [keys, {reset}] useKeyDownList();
> ```

That seems fine for this and many other cases, but still, the behaviour you experience is only on Mac, on windows the shortcut would never trigger, so still this wouldn't help.

> Another potential thing would be to reset the keydown list to only the keys we can know with 100% certainty are down when the meta key is lifted. Essentially remove any character key from the list since it is impossible to know if it is down and leads to unexpected behavior by keeping it in the list.

The thing is not every combination is impossible and it varies on systems, and actually with raw js `keydown` event you get the last key name + flags if the `ALT` `CONTROL` `META` & `SHIFT` are pressed, so with raw js checking if combination of these keys + single character key is pressed is relatively simple. So it could be "reset" to up to single character + any of these flags, but then you couldn't inverse order, eg. `M` + `META` + `SHIFT`, because last key `SHIFT` has no character, but that doesn't mean the other character `M` isn't still down. Also the `M` + `META` + `SHIFT` order doesn't trigger the system shortcut for me and is registered in js with the `useKeyDownList`. 

Ultimately I'd just avoid trying to detect system shortcuts in js, but I can't always know which combinations these are, so it'd good to have some default but with possibility to change it by the user.

**Comment by onx2** [comment]
I think the only solution for this, at least for me, is to reset the keys when the meta key is lifted and assume there is nothing we can do about it because a higher priority system needs control.

> Also the M + META + SHIFT order doesn't trigger the system shortcut for me and is registered in js with the useKeyDownList.

This is something related to another struggle of mine - I want to have any permutation of the keys in a shortcut to trigger a function. This is the behavior in VSCode, Zed, Firefox, etc.

> Ultimately I'd just avoid trying to detect system shortcuts in js, but I can't always know which combinations these are, so it'd good to have some default but with possibility to change it by the user.

This is fair. Also, I think I'm creating a problem that doesn't need to exist by trying to implement a keyboard shortcut override system for the user. JS just isn't really a great place for that 🤷🏼 


---

Thanks for talking this through with me. Do you think it would be valuable for me to open a PR to return `reset` in `useKeyDownList`?

**Comment by maciek50322** [comment]
>Thanks for talking this through with me. Do you think it would be valuable for me to open a PR to return reset in useKeyDownList?

Not sure, it would be breaking change, but I think a handful feature, you can try and see what others have to say
